### ISSUE TITLE
Doesn't work. Neglected. Abandoned.

### ISSUE THREAD

**Issue by stovenator** [stovenator/kungfuse#1]

**Comment by itdaniher** [comment]
Hey, I fixed up kungfuse some (at https://github.com/bazaar-projects/kungfuse) with Python3 support and some optimizations and a handful of other tweaks / adjustments / improvements.

It works pretty well for my needs.

Would you permit me to change the license to BSD? I'd like to incorporate my modified version (of your modified version of memory.py from the fusepy project) in a non-GPLed codebase.

Cheers!
Ian

edit: s/mem.py/memory.py/

**Comment by stovenator** [comment]
Sure, no problem. There were obvious problems and inconsistencies that I abandoned on this project. I'll change the license, and you're free to maintain as you see fit!

**Comment by itdaniher** [comment]
Thanks!
